services:
  - type: web
    name: personal-blog-hub
    env: node
    buildCommand: npm install && npm run build && npm run db:push
    startCommand: npm start
    envVars:

      - key: DATABASE_URL
        fromDatabase:
          name: personal-blog-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: postgres
    name: personal-blog-db
    plan: free
    ipAllowList: [] 
