services:
  - type: web
    name: personal-blog-hub
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    # Add this to ensure database is ready before web service
    dependsOn:
      - personal-blog-db
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: personal-blog-db
          property: connectionString
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SECRET_KEY_ACCESS_TOKEN
        sync: false
      - key: SECRET_KEY_REFRESH_TOKEN
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET_KEY
        sync: false
      - key: RESEND_API
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_ENDPOINT_WEBHOOK_SECRET_KEY
        sync: false

  - type: postgres
    name: personal-blog-db
    plan: free
    ipAllowList: []
